### ISSUE TITLE
关于头文件问题

### ISSUE THREAD

**Issue by GoingJack** [sprinfall/webcc#12]
你好，我尝试使用的你例子程序，但是我发现了好多关于头文件的问题。类似于这样
> In file included from hello_world_server.cc:2:0:
> webcc/response_builder.h:7:27: fatal error: webcc/request.h: 没有那个文件或目录
> #include "webcc/request.h"

的错误。
我把你的根目录下的`webcc`目录复制到了`example`目录底下,但是我又得到类似的错误是关于`webcc`里面的`.cc`文件 ，因为它包含的头文件目录也是`webcc/xxx`这个目录是找不到的，这是得都需要我手动编辑再更改码？还是说我哪里操作有误，因为我看到您得Readme文件也没有特殊说明，所以我特地来问下您。如果可以看到请帮助我解答一下，谢谢您。

**Comment by sprinfall** [comment]
不好意思，才看到你的问题。
简单来说，不管你把 webcc 目录放在那里，都需要把它的父目录加到头文件路径里。对 CMake 来说，就是 `include_directories()`，如果不用 CMake 直接用 VS，需要添加到 VS 的头文件目录里，GCC 下面也是类似这样。
为什么要加上 `webcc/` 前缀，是为了避免和你项目中其他同名文件相冲突。这种头文件包含的方式，也是 Google 推荐的做法。

**Comment by sprinfall** [comment]
我在这里有说明：https://github.com/sprinfall/webcc/wiki/Integrate-Into-Your-Project
