### ISSUE TITLE
Add as a subdirectory

### ISSUE THREAD

**Issue by SeanOMik** [sprinfall/webcc#16]
How could I add webcc as a subdirectory to my cmake project? I tried to do: 
```cmake
add_subdirectory(thirdparty/webcc)
# Later in the CMake
target_link_libraries(main PRIVATE webcc)
```
But I get errors when I try to include the library saying that that header doesn't exist.

**Comment by sprinfall** [comment]
You need to add more CMake statements for the configurations.
In order to answer your question, I just created a demo project: https://github.com/sprinfall/webcc-integration
I hope it helps.

**Comment by SeanOMik** [comment]
Sorry for taking so long to try it, but that did fix it.
