### ISSUE TITLE
https rest clients/servers 

### ISSUE THREAD

**Issue by happyturtle123** [sprinfall/webcc#2]
Hi Just having a look at the code in order to do a GET to a https endpoint would i need to do the following (assuming async).

1. create http_ssl_async_client.{cc,h} files which point to http_ssl_client.{cc,h}
2. create rest_async_client.{cc,h} which points to http_ssl_async_client.{cc,h}

Am i on the correct track?

Many thanks!

**Comment by sprinfall** [comment]
Yes. But I should have done that. Please note that the SSL part is still under development.

**Comment by umarmir** [comment]
just switched back to an old commit and my issue resolved.
i think issue is in latest code.

`git reset --hard 360d095`

**Comment by sprinfall** [comment]
SSL client has been supported. (NOTE: No async- API provided)
