### ISSUE TITLE
Transfer-Encoding: chunked" not handled properly

### ISSUE THREAD

**Issue by ReallyVirtual** [sprinfall/webcc#3]
HttpParser assumes that the Content-Length would always be present in the response, which is not the case if the Transfer-Encoding is "chunked" - and they are mutually exclusive.
If the server returned a "chunked" Transfer-Encoding, the end result is an empty response.

**Comment by sprinfall** [comment]
Thank you. I will add "chunked" support into the plan.

**Comment by sprinfall** [comment]
I just made a [push](https://github.com/sprinfall/webcc/commit/8d9855f7518bcfc9fa58f1b96cd4f4af46beb735) which includes the "chunked" support.
