### ISSUE TITLE
Persistent Connections

### ISSUE THREAD

**Issue by bkamba** [sprinfall/webcc#7]
Does the Http server for webcc support persistent connections?

**Comment by sprinfall** [comment]
Not yet. Sorry. I'm working the client side right now. I will let you know if the server side is ready.

**Comment by sprinfall** [comment]
> Does the Http server for webcc support persistent connections?

Hi, I just pushed a commit which includes a basic support for Persistent Connections in server side. You might have interest to have a look.

**Comment by bkamba** [comment]
Thanks!
